// mini2/src/components/Navbar.jsx
import React from 'react'
import { NavLink } from 'react-router-dom'

const Navbar = () => {
  return (
    <nav className='navbar navbar-expand-lg bg-body-tertiary'>
  <div className='container-fluid'>
    <NavLink className='navbar-brand'>Template</NavLink>
    <button className='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarNavAltMarkup' aria-controls='navbarNavAltMarkup' aria-expanded='false' aria-label='Toggle navigation'>
      <span className='navbar-toggler-icon'></span>
    </button>
    <div className='collapse navbar-collapse' id='navbarNavAltMarkup'>
      <div className='navbar-nav'>
        <NavLink to='/' className='nav-link' aria-current='page'>Home</NavLink>
        <NavLink to='/about' className='nav-link'>About</NavLink>
        <NavLink to='/contact' className='nav-link'>Contact</NavLink>
        <NavLink to='/dashboard' className='nav-link'>Dashboard</NavLink>
      </div>
    </div>
  </div>
</nav>
  )
}

export default Navbar

// vue-vite/src/components/NavBar.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <NavItem :pageName="link" v-for="(link, index) in links" :key="index"/>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</template>

<script>
import NavItem from "./NavItem.vue";
    export default {
        components: {
            NavItem,
        },

        data() {
            return {
                links: ["one", "two", "three", "four"]
            }
        },
    }
</script>

<style lang="scss" scoped>

</style>
